# github defaults
safe: true
lsi: false

# exclude meta files
exclude:
  - README.md
  - tests
  - target
  - "*.sh"
  - solr.cool.pem
  - Gemfile*

# put permalinks into subdirectory
permalink: /blog/:title.html

excerpt_separator: "<!--more-->"

timezone: Europe/Berlin
