# github defaults
safe: true
lsi: false

# exclude meta files
exclude: ['.project', 'README.md', 'Gemfile', 'Gemfile.lock', 'deploy.sh', 'Rakefile', 'images/team/_original', 'ansible.cfg']

# url
#url: https://developer.s24.com

# put permalinks into subdirectory
permalink: /blog/:title.html

excerpt_separator: "<!--more-->"

timezone: Europe/Berlin

# ---------------------------------------------------------------------
# add components here
# ---------------------------------------------------------------------
queryparsers:
  - name: Bmax Query Parser
    category: queryparsers
    description: A boosting dismax query parser for Apache Solr. The bmax query parser relies on field types  and tokenizer chains to parse the user query, discover synonyms, boost and penalize terms at  query time. Hence it is highly configurable. The lucene query composed is a boosted and  reranked dismax query with a minimum must match of 100%.
    pros: 
      - Simple searches
      - Ecommerce applications
      - Used in production
      - Updated within in the last 6 months
    cons: 
      - Native Lucene query syntax does not work
    solr_versions:
      - "4.10"
      - "5.x"
      - "6.x"
    installation: Solr Plugin (JAR)
    url: https://github.com/shopping24/solr-bmax-queryparser
    maven: "http://search.maven.org/#browse%7C-1697835338"
    source: https://github.com/shopping24/solr-bmax-queryparser
    build: https://travis-ci.org/shopping24/solr-bmax-queryparser
    build_status: https://travis-ci.org/shopping24/solr-bmax-queryparser.svg
    license: Apache License v2
    license_url: http://choosealicense.com/licenses/apache-2.0/

  - name: Querqy
    category: queryparsers
    description: Querqy is a framework for query preprocessing in Java-based search engines. It comes with a powerful, rule-based preprocessor named 'Common Rules Preprocessor', which provides query-time synonyms, query-dependent boosting and down-ranking, and query-dependent filters.
    pros: 
      - Used in production
      - Updated within in the last 6 months
    solr_versions:
      - "4.10"
      - "5.0"
    installation: Solr Plugin (JAR)
    url: https://github.com/renekrie/querqy
    source: https://github.com/renekrie/querqy
    build: https://travis-ci.org/renekrie/querqy
    build_status: https://travis-ci.org/renekrie/querqy.svg
    license: Apache License v2
    license_url: http://choosealicense.com/licenses/apache-2.0/

  - name: Lucene/Solr Synonym-Expanding EDisMax Parser
    category: queryparsers
    description: Solr query parser plugin that performs proper query-time synonym expansion.
    pros:
      - Supports phrases in query-time synonyms
      - Apply same synonyms across all fields
      - Simple setup
    cons:
      - Cannot tune synonyms per field
      - May generate huge queries
    solr_versions: 
      - "4.x"
      - "5.x"
      - "6.2"
    installation: Solr Plugin (JAR)
    url: http://nolanlawson.com/2012/10/31/better-synonym-handling-in-solr
    source: https://github.com/healthonnet/hon-lucene-synonyms
    license: Apache License v2
    license_url: http://choosealicense.com/licenses/apache-2.0/
    build: https://travis-ci.org/healthonnet/hon-lucene-synonyms
    build_status: https://travis-ci.org/healthonnet/hon-lucene-synonyms.svg

analyzers:
  - name: solr-analyzers
    category: analyzers
    description: A Solr analyzer collection of tokenizers and filters.
    pros: 
      - AnalyzingSentenceTokenizer to remove bad sentences from text
      - Used in production
      - Updated within in the last 6 months
    solr_versions:
      - "5.x"
      - "6.x"
    installation: Solr Plugin (JAR)
    url: https://github.com/shopping24/solr-analyzers
    maven: "http://search.maven.org/#browse%7C-1733826686"
    source: https://github.com/shopping24/solr-analyzers
    build: https://travis-ci.org/shopping24/solr-analyzers
    build_status: https://travis-ci.org/shopping24/solr-analyzers.svg
    license: Apache License v2
    license_url: http://choosealicense.com/licenses/apache-2.0/

  - name: solr-JDBC
    category: analyzers
    description: A Solr synonym and stopword filter for reading synonyms out of JDBC.
    pros: 
      - Pull synonyms via JDBC out of databases
      - Highly configurable, use SQL to retrieve synonyms
      - Used in production
      - Updated within in the last 6 months
    solr_versions:
      - "5.x"
      - "6.x"
    installation: Solr Plugin (JAR)
    url: https://github.com/shopping24/solr-jdbc
    maven: "http://search.maven.org/#browse%7C-1733826686"
    source: https://github.com/shopping24/solr-jdbc
    build: https://travis-ci.org/shopping24/solr-jdbc
    build_status: https://travis-ci.org/shopping24/solr-jdbc.svg
    license: Apache License v2
    license_url: http://choosealicense.com/licenses/apache-2.0/

searchcomponents:
  - name: Language Detection Component
    category: searchcomponents
    description: Solr search component for language detection.
    solr_versions:
      - "4.10"
    installation: Build Your Own
    url: https://gist.github.com/vsdev1/8397079
    source: https://gist.github.com/vsdev1/8397079
    license: Unknown

  - name: Request Sanitizer Component
    category: searchcomponents
    description: Solr search component for avoiding insane request params such as too large rows or offset params
    solr_versions:
      - "5.x"
      - "6.x"
    pros:
      - Override client request params in config
      - Harden RequestHandler endpoints without code
    installation: Solr Plugin (JAR)
    url: https://github.com/cominvent/request-sanitizer-component
    build: https://travis-ci.org/cominvent/request-sanitizer-component
    build_status: https://travis-ci.org/cominvent/request-sanitizer-component.svg
    source: https://github.com/cominvent/request-sanitizer-component
    license: Apache License v2
    license_url: http://choosealicense.com/licenses/apache-2.0/

other:
  - name: Thymeleaf response writer
    category: other
    description: A Solr response writer to use the Thymeleaf templating engine for HTML templating.
    pros: 
      - Easy templating in Thymeleaf
      - Used in production
      - Updated within in the last 6 months
    solr_versions:
      - "4.10"
      - "5.x"
      - "6.x"
    installation: Solr Plugin (JAR)
    url: https://github.com/shopping24/solr-thymeleaf
    maven: "http://search.maven.org/#browse%7C-1345016623"
    source: https://github.com/shopping24/solr-thymeleaf
    build: https://travis-ci.org/shopping24/solr-thymeleaf
    build_status: https://travis-ci.org/shopping24/solr-thymeleaf.svg
    license: Apache License v2
    license_url: http://choosealicense.com/licenses/apache-2.0/

  - name: "SolRDF: Apache Solr meets RDF"
    category: other
    description: SolRDF (i.e. Solr + RDF) is a set of Solr extensions for managing (index and search) RDF data.
    solr_versions:
      - "4.10"
    installation: Solr Plugin (JAR)
    url: https://github.com/agazzarini/SolRDF/wiki
    source: https://github.com/agazzarini/SolRDF
    build: https://travis-ci.org/agazzarini/SolRDF
    build_status: https://travis-ci.org/agazzarini/SolRDF.svg?branch=master
    license: Apache License v2
    license_url: http://choosealicense.com/licenses/apache-2.0/

  - name: Mapping Update Processor
    category: other
    description: The MappingUpdateProcessor lets you map value of a field to some other value based on a dictionary
    solr_versions:
      - "6.x"
    installation: Build Your Own
    url: https://github.com/cominvent/solr-update-processors
    source: https://github.com/cominvent/solr-update-processors
    build: https://travis-ci.org/cominvent/solr-update-processors
    build_status: https://travis-ci.org/cominvent/solr-update-processors.svg
    license: Apache License v2
    license_url: http://choosealicense.com/licenses/apache-2.0/